export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_PASSWORD_RESET_REQUIRED: 'AUTH_PASSWORD_RESET_REQUIRED',
  AUTH_TEMP_PASSWORD_EXPIRED: 'AUTH_TEMP_PASSWORD_EXPIRED',

  // User Management
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_DELETION_FAILED: 'USER_DELETION_FAILED',
  USER_ADMIN_DELETION_FORBIDDEN: 'USER_ADMIN_DELETION_FORBIDDEN',
  USER_SAME_PASSWORD: 'USER_SAME_PASSWORD',
  USER_INVALID_CURRENT_PASSWORD: 'USER_INVALID_CURRENT_PASSWORD',

  // Parcel Management
  PARCEL_NOT_FOUND: 'PARCEL_NOT_FOUND',
  PARCEL_CREATION_FAILED: 'PARCEL_CREATION_FAILED',
  PARCEL_UPDATE_FAILED: 'PARCEL_UPDATE_FAILED',
  PARCEL_DELETION_FAILED: 'PARCEL_DELETION_FAILED',
  PARCEL_INVALID_STATUS: 'PARCEL_INVALID_STATUS',
  PARCEL_RECEIVER_NOT_FOUND: 'PARCEL_RECEIVER_NOT_FOUND',
  PARCEL_ADMIN_RECEIVER_FORBIDDEN: 'PARCEL_ADMIN_RECEIVER_FORBIDDEN',
  PARCEL_SELF_SEND_FORBIDDEN: 'PARCEL_SELF_SEND_FORBIDDEN',
  PARCEL_TRACKING_INVALID: 'PARCEL_TRACKING_INVALID',

  // Parcel Requests
  PARCEL_REQUEST_NOT_FOUND: 'PARCEL_REQUEST_NOT_FOUND',
  PARCEL_REQUEST_CREATION_FAILED: 'PARCEL_REQUEST_CREATION_FAILED',
  PARCEL_REQUEST_UPDATE_FAILED: 'PARCEL_REQUEST_UPDATE_FAILED',
  PARCEL_REQUEST_DELETION_FAILED: 'PARCEL_REQUEST_DELETION_FAILED',
  PARCEL_REQUEST_INVALID_STATUS: 'PARCEL_REQUEST_INVALID_STATUS',
  PARCEL_REQUEST_NOT_APPROVED: 'PARCEL_REQUEST_NOT_APPROVED',
  PARCEL_REQUEST_ALREADY_PROCESSED: 'PARCEL_REQUEST_ALREADY_PROCESSED',
  PARCEL_REQUEST_ACCESS_DENIED: 'PARCEL_REQUEST_ACCESS_DENIED',

  // Email Services
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',
  EMAIL_INVALID_RECIPIENT: 'EMAIL_INVALID_RECIPIENT',
  EMAIL_SERVICE_UNAVAILABLE: 'EMAIL_SERVICE_UNAVAILABLE',

  // Maps & Geocoding
  MAPS_GEOCODING_FAILED: 'MAPS_GEOCODING_FAILED',
  MAPS_REVERSE_GEOCODING_FAILED: 'MAPS_REVERSE_GEOCODING_FAILED',
  MAPS_DISTANCE_CALCULATION_FAILED: 'MAPS_DISTANCE_CALCULATION_FAILED',
  MAPS_API_KEY_MISSING: 'MAPS_API_KEY_MISSING',
  MAPS_API_LIMIT_EXCEEDED: 'MAPS_API_LIMIT_EXCEEDED',
  MAPS_INVALID_COORDINATES: 'MAPS_INVALID_COORDINATES',
  MAPS_INVALID_ADDRESS: 'MAPS_INVALID_ADDRESS',

  // Validation Errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_TOO_SHORT: 'VALIDATION_PASSWORD_TOO_SHORT',
  VALIDATION_PASSWORD_TOO_LONG: 'VALIDATION_PASSWORD_TOO_LONG',
  VALIDATION_PHONE_INVALID: 'VALIDATION_PHONE_INVALID',
  VALIDATION_WEIGHT_INVALID: 'VALIDATION_WEIGHT_INVALID',
  VALIDATION_DATE_INVALID: 'VALIDATION_DATE_INVALID',
  VALIDATION_ENUM_INVALID: 'VALIDATION_ENUM_INVALID',

  // Database Errors
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  NULL_CONSTRAINT_VIOLATION: 'NULL_CONSTRAINT_VIOLATION',
  MISSING_REQUIRED_VALUE: 'MISSING_REQUIRED_VALUE',
  RELATION_VIOLATION: 'RELATION_VIOLATION',

  // File Operations
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_PROCESSING_FAILED: 'FILE_PROCESSING_FAILED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // External Services
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_PROCESSING_FAILED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  BAD_GATEWAY: 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
